// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABvH5TOQ-4P1cxzCMmyzNVkocs5FGs09c',
    appId: '1:861083253187:web:51c4a1e065109eaa8e2576',
    messagingSenderId: '861083253187',
    projectId: 'gdg-business-ai-assistant',
    authDomain: 'gdg-business-ai-assistant.firebaseapp.com',
    storageBucket: 'gdg-business-ai-assistant.firebasestorage.app',
    measurementId: 'G-2ZE1TWYVGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj5wCq2zpgQGjZHdWBpa2PYAtujmsjV64',
    appId: '1:861083253187:android:35aeed162264a9018e2576',
    messagingSenderId: '861083253187',
    projectId: 'gdg-business-ai-assistant',
    storageBucket: 'gdg-business-ai-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA69RG0ThHNxHSy8LqhZSXD3ciMEyT4apc',
    appId: '1:861083253187:ios:235ed5165ad9e6c98e2576',
    messagingSenderId: '861083253187',
    projectId: 'gdg-business-ai-assistant',
    storageBucket: 'gdg-business-ai-assistant.firebasestorage.app',
    iosBundleId: 'com.example.businessAiAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA69RG0ThHNxHSy8LqhZSXD3ciMEyT4apc',
    appId: '1:861083253187:ios:235ed5165ad9e6c98e2576',
    messagingSenderId: '861083253187',
    projectId: 'gdg-business-ai-assistant',
    storageBucket: 'gdg-business-ai-assistant.firebasestorage.app',
    iosBundleId: 'com.example.businessAiAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABvH5TOQ-4P1cxzCMmyzNVkocs5FGs09c',
    appId: '1:861083253187:web:66f33ef170b1311c8e2576',
    messagingSenderId: '861083253187',
    projectId: 'gdg-business-ai-assistant',
    authDomain: 'gdg-business-ai-assistant.firebaseapp.com',
    storageBucket: 'gdg-business-ai-assistant.firebasestorage.app',
    measurementId: 'G-8VXGQ6SEB1',
  );
}
